# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-28 06:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Paqueteria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cp_origen', models.IntegerField()),
                ('cp_destino', models.IntegerField()),
                ('peso', models.FloatField()),
                ('alto', models.FloatField()),
                ('largo', models.FloatField()),
                ('ancho', models.FloatField()),
            ],
        ),
    ]
